### PR TITLE
remove empty dotfile

### PR DESCRIPTION
**Pull request by quidame**
##### SUMMARY

Remove empty dotfile `changelogs/fragments/.empty`.

This file just triggers an error in Ansible Zuul check (this one from [ansible-test-sanity-docker-stable-2.10](https://dashboard.zuul.ansible.com/t/ansible/build/8360a320bfa144ab9795b7289bc0896f) that fails every time due to this file; see details below)

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

none

##### ADDITIONAL INFORMATION

```paste below
ERROR: Found 1 changelog issue(s) which need to be resolved:
ERROR: changelogs/fragments/.empty:0:0: file must not be a dotfile
...
ERROR: The 1 sanity test(s) listed below (out of 45) failed. See error output above for details.
changelog
...
ERROR: Command "docker exec 25871dd7204f98bdd84a35843a9f6f58f5359ded3e681ff033368a18b4af6bcc /usr/bin/env ANSIBLE_TEST_CONTENT_ROOT=/root/ansible_collections/ansible/posix LC_ALL=en_US.UTF-8 /usr/bin/python3.6 /root/ansible/bin/ansible-test sanity -vvvv --metadata tests/output/.tmp/metadata-4d42a7qp.json --truncate 0 --redact --color no --requirements" returned exit status 1.
ERROR
```

### CODE REVIEW

**Comment by quidame** [comment]
With this empty dotfile removed from `changelogs/fragments`, `ansible-test-sanity-docker-stable-2.10` now succeeds (https://dashboard.zuul.ansible.com/t/ansible/builds?job_name=ansible-test-sanity-docker-stable-2.10&project=ansible-collections/ansible.posix)

**Comment by quidame** [comment]
ready_for_review

**Comment by quidame** [comment]
bot_status

**Comment by quidame** [comment]
@maxamillion could you take a look, please ?

**Comment by Akasurde** [comment]
@quidame CI is failing due to sanity checks. I raised a PR to fix those checks - https://github.com/ansible-collections/ansible.posix/pull/138

**Comment by Akasurde** [comment]
Superseded by https://github.com/ansible-collections/ansible.posix/pull/145

@quidame Thanks for the contribution.

**Pull request closed without merging**
