### PR TITLE
sanity fixes for pylint test

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
changelogs/fragments/sanity_fixes.yml
tests/sanity/ignore-2.12.txt
tests/unit/mock/loader.py

### CODE REVIEW

**Comment by Akasurde** [comment]
cc @Andersson007

**Review by Andersson007 — APPROVED** [review]
LGTM

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
remove gate for the moment, to debug check jobs

**Comment by pabelanger** [comment]
looks to have cleared up

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
