### PR TITLE
firewalld: Add support for protocol parameter

### LINKED ISSUE #416: Support for --add-protocol (firewalld)
##### SUMMARY
Currently the Ansible firewalld module does not support the `--add-protocol` command line argument

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
firewalld

##### ADDITIONAL INFORMATION
This is needed if you want to add OSPF, for example:
```
firewall-cmd --add-protocol=ospf --zone=public
```

### PR DESCRIPTION
**Pull request by rsguhr**
##### SUMMARY
Fixes #416 - This PR implements the `--add-protocol`/`--remove-protocol` parameters for firewalld.
I have just copied and rewritten the code from service parameter. Please look carefully :)

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
firewalld

##### ADDITIONAL INFORMATION

```yaml
    - name: Allow OSPF traffic
      ansible.posix.firewalld:                                                  
        protocol: ospf                                                          
        zone: work                                                              
        state: enabled                                                          
        permanent: true 
```

### CODE REVIEW

**Comment by saito-hideki** [comment]
recheck

**Comment by rsguhr** [comment]
@saito-hideki did you have some time to look at this PR? :3

**Comment by saito-hideki** [comment]
@rsguhr sure, I'll check the following sanity test failure first :)
- [ansible-test-sanity-docker-stable-2.12](https://ansible.softwarefactory-project.io/zuul/build/09f3567ee86a44e3a2d16a35af335be8)
- [ansible-test-sanity-docker-stable-2.13](https://ansible.softwarefactory-project.io/zuul/build/711a015ac21145c6adebddf137fdf367)

**Review by saito-hideki — APPROVED** [review]
Thank you for your contribution! LGTM :)

**Comment by saito-hideki** [comment]
@rsguhr CI problem fixed and this PR has been merged. Thank you for the PR!

**Pull request merged**
