### PR TITLE
Trivial: missing FQCN in synchronize documentation seealso

### LINKED ISSUE #339: Broken link / wrong module name in synchronize module documentation See Also section
##### SUMMARY

The `synchronize` module documentation has invalid link in the "See also" section:
```yaml
- module: copy
```
Which in https://docs.ansible.com/ansible/latest/collections/ansible/posix/synchronize_module.html#ansible-collections-ansible-posix-synchronize-module renders into:
```
M(copy)
```
It displays exactly like that and doesn't linkify, maybe because it is not using FQCN?

```
<!--- HINT: Did you know the documentation has an "Edit on GitHub" link on every page ? -->
```
No it does not! Maybe this "every page" refers to pages outside collections?  
In the link above I could not find anything when searching for "edit".

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

synchronize

##### ANSIBLE VERSION

```paste below
irrelevant, confirmed the error in `main` branch also
```

### PR DESCRIPTION
**Pull request by bluikko**
##### SUMMARY

See Also section module name missing namespace so make it into FQCN.

Fixes #339

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

synchronize

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Akasurde** [comment]
recheck

**Comment by saito-hideki** [comment]
Closing and reopening for CI trigger

**Review by saito-hideki — CHANGES_REQUESTED** [review]
@bluikko Hi, thank you for the contribution.
1. If it is possible, can you rebase this PR with the latest main branch?
2. Then, you need to add the changelog fragments file according to the following link: https://docs.ansible.com/ansible/latest/community/development_process.html#creating-changelog-fragments

Note: you can choose `trivial:` like this: https://github.com/ansible-collections/ansible.posix/blob/main/changelogs/fragments/401_document_module_default_values.yml

**Comment by saito-hideki** [comment]
recheck

**Comment by saito-hideki** [comment]
The original issue #339 has been fixed by #413.
So I'm closing this PR. Thank you for your contribution.

**Comment by bluikko** [comment]
Hmpf, somehow I had missed all the comments - I am pretty sure I did not see the e-mail notifications from GitHub. Will need to investigate that at some point. I could have rebased & added a fragment.  
Good that someone else made a proper PR but unfortunate that it resulted in extra work for everyone.

**Comment by saito-hideki** [comment]
@bluikko Eventually, the codebase was fixed based on your contributions. We are grateful to you :)

**Pull request closed without merging**
