### PR TITLE
Update AZP config

### LINKED ISSUE #236: Update test matrix is required
##### SUMMARY
For details https://github.com/ansible-collections/overview/issues/45#issuecomment-889538991

### PR DESCRIPTION
**Pull request by saito-hideki**
##### SUMMARY

* Fixes ansible-collections/overview#45
* Fixes #236

##### DESCRIPTION
The following changes are for the `devel` version test sections:

- [x] Remove: fedora32
- [x] Remove: freebsd/11.4
- [x] Remove: rhel/8.3
- [x] Add: fedora34
- [x] Add: freebsd/13.0
- [x] Add: rhel/8.4

##### ISSUE TYPE
- Test Pull Request

##### COMPONENT NAME
CI

### CODE REVIEW

**Comment by Akasurde** [comment]
@saito-hideki Awesome. Thanks for taking care of this.

**Review by Andersson007 — COMMENTED** [review]
at least there's same issue as https://github.com/ansible-collections/overview/issues/179

**Comment by saito-hideki** [comment]
@Andersson007 Yeah, I'll report it as a comment to ansible-collections/overview#179 :)

**Comment by saito-hideki** [comment]
Closing and re-opening for CI trigger.

**Comment by saito-hideki** [comment]
Closing and re-opening for CI trigger.

**Comment by saito-hideki** [comment]
@Akasurde @Akasurde, CI process seems fixed. I would appreciate it if you guys review this PR :)

**Review by Andersson007 — APPROVED** [review]
LGTM

**Pull request merged**
