### PR TITLE
[CI] Fixed documentation and options to address new sanity tests

### PR DESCRIPTION
**Pull request by saito-hideki**
##### SUMMARY

Fixed documentation and options to address new sanity tests:

- Addresses #348 
- https://docs.ansible.com/ansible/latest/dev_guide/testing_validate-modules.html

##### ISSUE TYPE
- CI tests Pull Request

##### COMPONENT NAME
- ansible.posix

##### ADDITIONAL INFORMATION
None

### CODE REVIEW

**Comment by saito-hideki** [comment]
Hi @Akasurde @Andersson007 
I have filed this PR to address new sanity test guidelines in `ansible-test-sanity-docker-devel`. And I would appreciate it if you could review this :)

Thanks!

**Review by Andersson007 — APPROVED** [review]
@saito-hideki thanks for the contribution! LGTM
Not sure, maybe it's also worth checking if the removal of `skippy` has been announced via the changelog before? If not, i would add an entry to the fragment with the `major_changes` tag and release the next (not major release) now so that the entry will end up in the collection's changelog.

**Review by Akasurde — APPROVED** [review]

**Comment by Akasurde** [comment]
@saito-hideki Thanks for putting this together.

**Comment by saito-hideki** [comment]
Closing and reopening for CI trigger

**Comment by saito-hideki** [comment]
recheck

**Comment by goneri** [comment]
You need to configure a branch protection rule like this:

image

**Comment by saito-hideki** [comment]
@gundalow @goneri it worked! thanks! :)

**Pull request merged**
