### PR TITLE
Changed the type of the forward and masquerade options from str to bool

### LINKED ISSUE #582: ansible.posix v 1.6.0 new forward option has wrong type
##### SUMMARY
Documentation in ansible/posix/plugins/modules/firewalld.py is incorrect
```
    forward:
    description:
      - The forward setting you would like to enable/disable to/from zones within firewalld.
      - This option only is supported by firewalld v0.9.0 or later.
    type: str
```
Should be
```
    forward:
    description:
      - The forward setting you would like to enable/disable to/from zones within firewalld.
      - This option only is supported by firewalld v0.9.0 or later.
    type: bool
```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
ansible.posix.firewalld

##### ANSIBLE VERSION
ansible.posix          1.6.0

### PR DESCRIPTION
**Pull request by saito-hideki**
##### SUMMARY

The forward and masquerade options for the firewall module takes either True or False as a value.
Currently, it is defined as a string, but it should be a boolean.

* Fixes #582

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
- ansible.posix.firewalld

##### ADDITIONAL INFORMATION
```paste below
None
```

### CODE REVIEW

**Review by maxamillion — APPROVED** [review]

**Comment by maxamillion** [comment]
LGTM 👍

**Comment by Andersson007** [comment]
reviewing, please don't merge

**Comment by Andersson007** [comment]
@saito-hideki hi, thanks for pinging!

1. the warning https://github.com/ansible-collections/ansible.posix/blob/ad2ac28ba6561a732fbf02376c1776c2bce7781b/plugins/modules/firewalld.py#L1137
was added by Gerlof Fokkema 2024-06-11 that doesn't feel long enough
2. I think this change is potentially breaking. How about changing the fragment for the change to be under `breaking_changes:` and releasing it in the next major release, i.e. 2.0.0 (if it's not expected soon)?

You have stable-1 for version 1.* releases, right? So if you agree with my proposal you could remove that warning as well and merge the PR to main but not backporting it to stable-1.
Thoughts folks?

**Comment by Andersson007** [comment]
btw also spotted that the `masquerade` option has the same properties, there's also a warning

**Comment by saito-hideki** [comment]
@maxamillion @Andersson007 Thanks for your review comment!

@Andersson007 I agree 100% with your advice. 
1. This PR should target the main branch for the next 2.0.0 release as  breaking_changes.
2. I will remove the warning message
3. Also, I will treat the masquerade option too.

After I address the above points, I will send the re-review request to you guys :)

**Comment by Andersson007** [comment]
@saito-hideki sounds like a plan, thanks!

**Comment by saito-hideki** [comment]
@maxamillion @Andersson007 I have fixed the PR and would appreciate it if you could review it again.

**Review by Andersson007 — APPROVED** [review]
@saito-hideki LGTM, thanks!

**Review by maxamillion — APPROVED** [review]
LGTM 👍

**Comment by saito-hideki** [comment]
@Andersson007 @maxamillion, thanks for the review.
It has been merged. the main branch :)

**Comment by Andersson007** [comment]
@saito-hideki thanks for the contribution!

**Pull request merged**
