### PR TITLE
Update OS as per guidelines

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
.azure-pipelines/azure-pipelines.yml

### CODE REVIEW

**Comment by Akasurde** [comment]
As per requirements - https://github.com/ansible-collections/overview/issues/45#issuecomment-776859063

**Comment by Andersson007** [comment]
@Akasurde will you continue to work on this? (the deadline is on March 1st)

**Comment by Akasurde** [comment]
> @Akasurde will you continue to work on this? (the deadline is on March 1st)

Yes I am. I waiting for https://github.com/ansible/ansible/pull/73609 to get merged. Since this change is required to resolve the CI failures.

Meanwhile, can you please review this PR? Thanks in advance.

**Review by Andersson007 — APPROVED** [review]

**Comment by gundalow** [comment]
Zuul is running CI against `devel` though https://github.com/ansible-collections/ansible.posix/blob/e1dad76ccbe1f1f43babb1774e407d8583e61405/meta/runtime.yml#L2 says the collection isn't supported there.
```
ERROR: Output on stderr from ansible-doc is considered an error.

Command "ansible-doc -t callback ansible.posix.cgroup_perf_recap ansible.posix.debug ansible.posix.json ansible.posix.profile_roles ansible.posix.profile_tasks ansible.posix.skippy ansible.posix.timer" returned exit status 0.
>>> Standard Error
[WARNING]: Collection ansible.posix does not support Ansible version
2.11.0.dev0
```

**Comment by gundalow** [comment]
recheck

**Comment by Andersson007** [comment]
@Akasurde thanks for doing it!
(and a reminder to mark ansible.posix as resolved there https://github.com/ansible-collections/overview/issues/45#issuecomment-776859063)

**Pull request merged**
