### PR TITLE
Fix json callback for non-lockstep strategy plugins such as free

### PR DESCRIPTION
**Pull request by sivel**
##### SUMMARY
Fix json callback for non-lockstep strategy plugins such as free. Fixes #65931

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
lib/ansible/plugins/callback/json.py

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by sivel** [comment]
Migrated from https://github.com/ansible/ansible/pull/65973

**Comment by gundalow** [comment]
@sivel Who would be good to review this? No maintainers are defined

**Comment by sivel** [comment]
Technically speaking the content teams own this repo now, so as a supported collection, someone from within that team I imagine.

**Comment by maxamillion** [comment]
recheck

**Pull request merged**
