### PR TITLE
csh: Define ``ECHO`` and ``COMMAND_SEP``

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

Fixes: #204

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
changelogs/fragments/204_csh_shell.yml
plugins/shell/csh.py

### CODE REVIEW

**Comment by Akasurde** [comment]
Before fix - 

```
'ShellModule' object has no attribute 'ECHO'
```

**Comment by Akasurde** [comment]
cc @quidame @bcoca @saito-hideki

**Review by saito-hideki — APPROVED** [review]
@Akasurde Thank you for the PR!
LGTM, and this fix is working without any issue on my end.

**Review by bcoca — APPROVED** [review]

**Comment by Akasurde** [comment]
@saito-hideki @bcoca Thanks for the review.

**Pull request merged**
