### PR TITLE
[WIP] Added handling ansible_ssh_host the same as ansible_host

### LINKED ISSUE #298: Synchronize module Unrecognized alias
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Synchronize 

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.6] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/python3/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible
  python version = 3.9.0 (default, Nov 30 2021, 19:05:25) [GCC 10.3.0]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

centos7

##### STEPS TO REPRODUCE

```yaml
Inventory
[test]
test-api-pre-01 ansible_ssh_host=10.200.75.213

cmd
ansible test -m ansible.posix.synchronize -a 'src=/root/cert-forensics-tools-release-el7.rpm dest=/tmp/ compress=yes'
```

##### EXPECTED RESULTS

In ansible 2.9, there is no problem with synchronization using aliases

##### ACTUAL RESULTS

```paste below
# ansible test -m ansible.posix.synchronize -a 'src=/root/cert-forensics-tools-release-el7.rpm dest=/tmp/ compress=yes' -vvv
ansible [core 2.11.6] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/python3/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /bin/ansible
  python version = 3.9.0 (default, Nov 30 2021, 19:05:25) [GCC 10.3.0]
  jinja version = 3.0.3
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
[DEPRECATION WARNING]: COMMAND_WARNINGS option, the command warnings feature is being removed. This feature will be removed from ansible-core in version 2.14. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
setting up inventory plugins
host_list declined parsing /root/hosts as it did not pass its verify_file() method
script declined parsing /root/hosts as it did not pass its verify_file() method
auto declined parsing /root/hosts as it did not pass its verify_file() method
Parsed /root/hosts inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/local/python3/lib/python3.9/site-packages/ansible/plugins/callback/minimal.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
META: ran handlers
Loading collection ansible.posix from /usr/local/python3/lib/python3.9/site-packages/ansible_collections/ansible/posix
Using module file /usr/local/python3/lib/python3.9/site-packages/ansible_collections/ansible/posix/plugins/modules/synchronize.py
Pipelining is enabled.
<10.200.75.213> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.200.75.213> EXEC /bin/sh -c '/usr/local/python3/bin/python3.9 && sleep 0'
test-api-pre-01 | FAILED! => {
    "changed": false,
    "cmd": "/bin/rsync --delay-updates -F --compress --archive --rsh='/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --out-format='<<CHANGED>>%i %n%L' /root/cert-forensics-tools-release-el7.rpm test-api-pre-01:/tmp/",
    "invocation": {
        "module_args": {
            "_local_rsync_password": null,
            "_local_rsync_path": "rsync",
            "_substitute_controller": false,
            "archive": true,
            "checksum": false,
            "compress": true,
            "copy_links": false,
            "delay_updates": true,
            "delete": false,
            "dest": "test-api-pre-01:/tmp/",
            "dest_port": null,
            "dirs": false,
            "existing_only": false,
            "group": null,
            "link_dest": null,
            "links": null,
            "mode": "push",
            "owner": null,
            "partial": false,
            "perms": null,
            "private_key": null,
            "recursive": null,
            "rsync_opts": [],
            "rsync_path": null,
            "rsync_timeout": 0,
            "set_remote_user": true,
            "src": "/root/cert-forensics-tools-release-el7.rpm",
            "ssh_args": null,
            "ssh_connection_multiplexing": false,
            "times": null,
            "verify_host": false
        }
    },
    "msg": "ssh: Could not resolve hostname test-api-pre-01: Name or service not known\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(226) [sender=3.1.2]\n",
    "rc": 255
}

```

### PR DESCRIPTION
**Pull request by saito-hideki**
##### SUMMARY
Currently, synchronize action plugin only handle `ansible_host` or `inventory_host` as a remote dest.
`ansible_ssh_host` will be deprecated, but it is still available in the current ansible-core devel version. Therefore, it should be handled in the same as `ansible_host`.

- Fixes #298

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
ansible.posix.synchronize

##### ADDITIONAL INFORMATION
```
None
```

### CODE REVIEW

**Comment by saito-hideki** [comment]
Closing and reopening for CI trigger

**Comment by saito-hideki** [comment]
@Akasurde @Andersson007 @felixfontein If you have time, I would appreciate it if you could review my PR :)

**Comment by felixfontein** [comment]
I'm not very familiar with these things, just wanted to add that as long as this collection still supports Ansible 2.9, ansible-base 2.10, ansible-core 2.11 and ansible-core 2.12, it should support all aliases available in these versions.

**Comment by saito-hideki** [comment]
@felixfontein  thank you for your advice. Yeah, I think so too, it should be supported `ansible_ssh_host`(and some other options) as the same as ssh connection plugin :)

**Comment by Andersson007** [comment]
it was removed in https://github.com/ansible-collections/ansible.posix/pull/159, maybe there's something else that can be put back? @saito-hideki could you please take a look
(cc @quidame @Akasurde)

**Comment by saito-hideki** [comment]
@Andersson007 thank you for your advice. I missed #159 :)

@Akasurde @quidame For backward compatibility, what do you think about the idea to allow both keywords?
1. ansible_ssh_port vs ansible_port
2. ansible_ssh_host vs ansible_host
3. ansible_ssh_user vs ansible_user

**Comment by saito-hideki** [comment]
I was trying to revert ansible_ssh_ *, however, based on the advice from @Andersson007 , I confirmed that it was intentionally removed in # 159. Apparently, I was trying to revive an ancient dinosaur, but I decided that is not reasonable so far.
I'm closing this PR without merging :)

**Pull request closed without merging**
