### PR TITLE
Fix boolean values in docs

### LINKED ISSUE #397: Consider using true/false for all booleans in docs
##### SUMMARY

Based on the [community decision](https://github.com/ansible-community/community-topics/discussions/120) to use `true/false` for boolean values in documentation and examples, we ask that  you evaluate booleans in this collection and consider changing any that do not use `true/false` (lowercase).

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

docs
##### ANSIBLE VERSION

```paste below
2.14
```

### PR DESCRIPTION
**Pull request by vladislav-sharapov**
##### SUMMARY
Fixes #397

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
Docs of several modules

##### ADDITIONAL INFORMATION
Notes about testing. I'm not sure how to test collections properly. I have ran `ansible-test sanity --python 3.10` and `ansible-test units --python 3.10` in venv with `ansible-core 2.14` (with 0 return code in both cases). To run units test successfully I had to install `pytest-forked` pip package in addition to this one `pytest-xdist` from [test-requirements.txt](https://github.com/ansible-collections/ansible.posix/blob/main/test-requirements.txt#L2).

Note about issue #397. I haven't changed `yes` [here](https://github.com/ansible-collections/ansible.posix/blob/main/plugins/modules/mount.py#L97) because in this case it is value from `/etc/vfstab`. Also I've changed `yes` for parameters `masquerade` and `icmp_block_inversion` because they both are converted to bool by `boolean` function and will be changed to boolean in a future release ([1](https://github.com/ansible-collections/ansible.posix/blob/main/plugins/modules/firewalld.py#L864), [2](https://github.com/ansible-collections/ansible.posix/blob/main/plugins/modules/firewalld.py#L989)), for `required` too.

### CODE REVIEW

**Comment by samccann** [comment]
Thanks @vladislav-sharapov for taking on this  and changing the booleans for this collection. I don't unfortunately know what's causing the CI failures but hoping someone else can pipe in on this to help out.

**Comment by briantist** [comment]
The sanity failures show these messages:

> ERROR: plugins/modules/acl.py:0:0: doc-default-does-not-match-spec: Argument 'entity' in argument_spec defines default as ('') but documentation defines default as (None)
> ERROR: plugins/modules/rhel_rpm_ostree.py:0:0: doc-default-does-not-match-spec: Argument 'name' in argument_spec defines default as ([]) but documentation defines default as (None)

These don't look like they are based on this PR; the history looks like the last commit also may have failed, I would ignore these for now until the project maintainers can comment.

The other failure is because this PR is missing a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-changelog-fragments).

**Comment by felixfontein** [comment]
These sanity errors remind me of https://github.com/ansible-collections/news-for-maintainers/issues/25 :)

**Comment by felixfontein** [comment]
#403 should fix the sanity tests.

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
recheck

**Comment by vladislav-sharapov** [comment]
I suppose build has failed because of this issue https://github.com/uqfoundation/dill/issues/514. I see `dill-0.3.5.1` in build log, this problem should be fixed in `dill-0.3.6`.

**Comment by saito-hideki** [comment]
@vladislav-sharapov Hi, I think there are two issues [a] and [b].

- [a] As you posted out, it related dill version issue,but this test is `non-voting`. So we can ignore it at this time: https://ansible.softwarefactory-project.io/zuul/build/0c7737932d924be48af489c8f6664375
- [b] It probably the integration test issue for firewall module on RHEL9(https://dev.azure.com/ansible/ansible.posix/_build/results?buildId=63072&view=logs&jobId=949dd205-d835-55f0-9652-ccba8c57c9c2&j=949dd205-d835-55f0-9652-ccba8c57c9c2&t=e496763b-41b9-58d8-cd3f-c7f71828f9bd)

We are checking [b] and will get back to you when we have resolved this issue.
Thanks!

**Comment by felixfontein** [comment]
The dill version has long been fixed in ansible-core devel. It's just that the milestone branch is way behind both devel and stable-2.14... (its state is three weeks before 2.14.0 has been released; according to https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/roadmap/ROADMAP_2_15.rst#development-phase it will be updated in four days.)

**Review by saito-hideki — APPROVED** [review]
LTGM

**Pull request merged**
