### PR TITLE
firewalld: Ensure idempotency

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

Use APIs like ``query*`` instead of ``get*``.

Fixes: #179

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
plugins/modules/firewalld.py
tests/integration/targets/firewalld/tasks/main.yml
tests/integration/targets/firewalld/tasks/port_forward_test_cases.yml
tests/integration/targets/firewalld/tasks/port_test_cases.yml
tests/integration/targets/firewalld/tasks/run_all_tests.yml

### CODE REVIEW

**Comment by Akasurde** [comment]
@quidame @aminvakil Could you please review this and let me know? Thanks in advance.

**Comment by mwperina** [comment]
As this is a regression, it should really be backported also to Ansible 2.9.z

**Review by quidame — APPROVED** [review]
@Akasurde thanks for fixing this ! looks good to me

**Review by aminvakil — COMMENTED** [review]
Thanks for fixing this!
Change looks good to me, but changelog fragment needs to be changed IMHO.

**Review by aminvakil — APPROVED** [review]
Thanks for adding this! LGTM

**Comment by aminvakil** [comment]
P.S.
Can I ask what's the reason of force-pushing on each commit? :) This makes it hard for me at least to follow the changes in every commit.

**Review by mnecas — APPROVED** [review]
LGTM

**Review by mwperina — APPROVED** [review]
Looks good to me, thanks

**Pull request merged**
