### PR TITLE
synchronize: correct typo

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
plugins/modules/synchronize.py

### CODE REVIEW

**Comment by Akasurde** [comment]
cc @felixfontein Thanks for noticing and reporting.

**Review by felixfontein — APPROVED** [review]

**Comment by aminvakil** [comment]
@felixfontein Oops!
Thanks for fixing this!

**Review by aminvakil — APPROVED** [review]

**Comment by felixfontein** [comment]
CI is failing because this has no changelog fragment (https://12c2b3753b797dd1aae7-5b6b5ba809450e924a1ea86bbbb7afec.ssl.cf1.rackcdn.com/198/62277ba8533d0299d7b139df3ecf8853cf0a5f5e/check/ansible-changelog-fragment/1fdbbeb/job-output.html#l81). I guess you could add one with category `trivial:`.

**Comment by Akasurde** [comment]
🤦🏼

**Comment by Akasurde** [comment]
@felixfontein Thanks. I should have seen that before.

**Comment by felixfontein** [comment]
@Akasurde thanks for fixing this!
@aminvakil thanks for reviewing!

**Pull request merged**
